### ISSUE TITLE
Swift 4.2 Compilation errors trying to build in Debug

### ISSUE THREAD

**Issue by NerdBird** [KrakenDev/PrediKit#11]
In the latest swift migration there are two lies of code in #IF DEBUG blocks that weren't migrated along with the rest. This causes compilation errors when trying to build in debug.

I have the fix done locally for normal development, but it would be nice to fix for first pod installs and the like.

The problems are in MemberQuery.swift on line 48 and PredicateBuilder.swift on line 150. Both require changing `String(type)` to `String(describing: type)`

**Comment by hectormatos2011** [comment]
Thanks @NerdBird! I'll merge this right now and submit a release

**Comment by hectormatos2011** [comment]
Quick update: Apparently, past Hector decided it would be a good idea to convert the library to support type safe key paths and got a new computer since. It's almost done but I'll keep you updated!

**Comment by hectormatos2011** [comment]
Alright cool it's in master now @NerdBird! I need to run the upload tool for publishing to Cocoapods but it should already start working for Swift Package Manager and Carthage if you're using either of those

**Comment by NerdBird** [comment]
Awesome! Thanks, pulling from master now and its all good for me 👍
