### ISSUE TITLE
Builder needs method for querying object properties

### ISSUE THREAD

**Issue by djbe** [KrakenDev/PrediKit#4]
Case where we want to query an object with related objects, such as:

``` Swift
class Captain: NSObject {
    var name: String
}
class Ship: NSObject {
    var captain: Captain
}
NSPredicate(format: "captain == %@", someCaptain)
NSPredicate(format: "captain.name == 'Chief Supreme'")
```

There currently is no method to match an object property (example 1), or to match a related object's property (example 2).

Are there currently any plans for this?

**Comment by hectormatos2011** [comment]
I completely forgot about this! I'll put one in tonight for you

**Comment by hectormatos2011** [comment]
Any opinions on syntax? At the moment you can achieve this by dropping down into strings as well. `includeIf.string("captain.name").isEqualTo("Chief Supreme")`

**Comment by hectormatos2011** [comment]
At the moment I'm thinking something along the lines of this:

``` swift
NSPredicate(Ship.self) { includeIf in
    includeIf.memberObject(Captain.self).string("name").isEqualTo("Chief Supreme")
}
```

**Comment by hectormatos2011** [comment]
@djbe

**Comment by dariopellegrini** [comment]
I think you’re sending messages to the wrong person.

Dario Pellegrini

http://www.dariopellegrini.com

**Comment by hectormatos2011** [comment]
Oops! Sorry but the username for the OP is @djbe. Is that yours as well?

**Comment by hectormatos2011** [comment]
GitHub is showing David Jennes for that username

**Comment by dariopellegrini** [comment]
I think it’s because I’ve set as favorite this library. Sorry, I didn’t remember that. However that’s not my username

Dario Pellegrini

http://www.dariopellegrini.com

**Comment by djbe** [comment]
@dariopellegrini He was actually mentioning me, not you :-)

@hectormatos2011 Your syntax suggestion looks great, although I'd make a small change. I wouldn't work with the class  type for properties, the property might have a different name (such as "captain1" or "reserveCaptain"). It might be better to just use strings for property names (until we get #selector syntax for getters):

``` swift
includeIf.memberObject("captain").string("name").isEqualTo("Chief Supreme")
-->
NSPredicate(format: "captain.name == 'Chief Supreme'")
```

 How would you handle the first predicate? You'd still need a call to test object equality, regardless of basic types. Something along the lines of:

``` swift
includeIf.object("captain").isEqualTo(someCaptain)
-->
NSPredicate(format: "captain == %@", someCaptain)
```

**Comment by hectormatos2011** [comment]
I think I have an idea for it. I'll submit a PR and how would feel about reviewing it?

**Comment by hectormatos2011** [comment]
@djbe

**Comment by hectormatos2011** [comment]
Alright so I just pushed a new version. It should now be available in PrediKit 2.0.3.

**Comment by djbe** [comment]
@hectormatos2011 Looks great!
I'll try to integrate PrediKit in one of our more complex apps and see if I hit any issues.

**Comment by hectormatos2011** [comment]
Sounds great! Feel free to continue creating issues! And let me know how it goes!
