### ISSUE TITLE
Minimal iOS version that PreditKit supports

### ISSUE THREAD

**Issue by av0c0der** [KrakenDev/PrediKit#6]
I used `PrediKit` in two projects installed through `CocoaPods`.

In my new one I used `Carthage` and now `XCode` throws an error: `Module file's minimum deployment target is ios8.3 v8.3: .../Carthage/Build/iOS/PrediKit.framework/Modules/PrediKit.swiftmodule/i386.swiftmodule`

What I'm doing wrong or did in my previous two projects?

**Comment by hectormatos2011** [comment]
What is the minimum iOS target that your project supports?

**Comment by hectormatos2011** [comment]
Carthage installs based on the project included in the repo. The project in the repo supports a minimum of iOS 8.3

**Comment by av0c0der** [comment]
The minimum target of my project is 8.0

**Comment by av0c0der** [comment]
I changed minimum target version of included project and builded `PrediKit` again and it works as expected (as I see).

Why you set iOS 8.3 as a target in that project?

**Comment by hectormatos2011** [comment]
There was a reason for it at the time but for the life of me I can't recall why. I will update it to using iOS 8.0 only and then push up the change.

**Comment by hectormatos2011** [comment]
Fixed with the last release.
